# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4894b84c040f59fbcfdf9ff8f3be1628b240eb2f2cf48576785e59e0d18ad4a49948b836e717eb6f02add3175938a3a2a22213aa4e67d0d9b79e41c6768e32f2

test:
  secret_key_base: 557900ffe23a1c300ac443b40afc86e3eb2135f7135e73e85a56f615e67af29088279bf608619d6f4a1f819cfd9f9faa841a23c2d0cd27e4333590f29b2a4fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
